#!/bin/bash

set -xe
CI=true

source ${OPENSHIFT_HOMEDIR}app-root/runtime/dependencies/python/virtenv/bin/activate

pip install -U pip setuptools
pip install --no-deps -Ur ${OPENSHIFT_REPO_DIR}/requirements.txt
pip install -Ue ${OPENSHIFT_REPO_DIR}

pushd ${OPENSHIFT_DATA_DIR}
if ! [ -d node ]; then
    wget https://nodejs.org/dist/v4.2.2/node-v4.2.2-linux-x64.tar.gz
    tar xvzf node-v4.2.2-linux-x64.tar.gz
    ln -sfn node-v4.2.2-linux-x64 node
fi
popd

pushd ${OPENSHIFT_REPO_DIR}
PATH="${OPENSHIFT_DATA_DIR}node/bin:$PATH"
HOME=$OPENSHIFT_DATA_DIR
npm install bower
npm install
node_modules/.bin/bower install

if [ -f ${OPENSHIFT_DATA_DIR}sentry ]; then
    pip install raven
fi
popd

python ${OPENSHIFT_REPO_DIR}/manage.py migrate --noinput

mkdir -p ${OPENSHIFT_DATA_DIR}media
ln -sf ${OPENSHIFT_DATA_DIR}media ${OPENSHIFT_REPO_DIR}wsgi/static/media
